
spring:
  devtools:
    restart:
      pollInterval: 4000

  datasource:
    username: credan_user
    password: 1zhida**
    url: jdbc:log4jdbc:mysql://uapi.credan.com:3307/credan?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

watch:
  path: /Users/gang/Downloads

server:
  port: 8080
