
spring:
  devtools:
    restart:
      pollInterval: 1000

  datasource:
    username: credan_user
    password: 1zhida**
    url: jdbc:log4jdbc:mysql://114.55.21.198:3306/credan?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

watch:
  path: D:/json_import

server:
  port: 8080
