
spring:
  devtools:
    restart:
      pollInterval: 4000

  datasource:
    username: root
    password: 123456
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/db_auth?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

watch:
  path: c:/Users/Administrator/Downloads

server:
  port: 8080
